services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    command: ["mongod", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: whisper
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet --port 27017
      interval: 5s
      timeout: 30s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/data

volumes:
  mongo_data:
  mongo_config:
  redis_cache:
    driver: local

