name: Publish Docker image to GHCR

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: false 
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tags
        id: vars
        run: |
          if [ -n "${{ inputs.VERSION }}" ]; then
            echo "TAGS=ghcr.io/${{ github.repository }}:${{ inputs.VERSION }}" >> $GITHUB_OUTPUT
          else
            echo "TAGS=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
          cache: true

      - name: Install dependencies
        working-directory: ./api
        run: go mod download

      - name: Build binaries
        working-directory: ./api
        run: |
          echo "Building version ${VERSION}..."
          make build
          echo "Build complete."

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
